# Generated by Django 4.2.28 on 2026-09-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название серии')),
                ('season', models.PositiveIntegerField(verbose_name='Сезон')),
                ('episode_number', models.PositiveIntegerField(verbose_name='Номер серии')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('air_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='episodes/screenshots/', verbose_name='Скриншот')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='episodes/videos/', verbose_name='Видео файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('characters', models.ManyToManyField(blank=True, related_name='episodes', to='characters.character', verbose_name='Персонажи в серии')),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серии',
                'ordering': ['season', 'episode_number'],
            },
        ),
    ]
